<?php

function get_file_name($file)
{
    global $site_config;

    switch ($file) {
        case 'chat_css_trans':
            return "{$site_config['paths']['baseurl']}/css/1/chat_trans_47050709.css";
        case 'chat_css_uranium':
            return "{$site_config['paths']['baseurl']}/css/1/chat_uranium_eda4e810.css";
        case 'css':
            return "{$site_config['paths']['baseurl']}/css/1/css_32d981ef.css";
        case 'vendor_css':
            return "{$site_config['paths']['baseurl']}/css/1/vendor_0adb4a45.css";
        case 'sceditor_css':
            return "{$site_config['paths']['baseurl']}/css/1/sceditor_12937e8b.css";
        case 'main_css':
            return "{$site_config['paths']['baseurl']}/css/1/main_2a78e486.css";
        case 'main_js':
            return "{$site_config['paths']['baseurl']}/js/1/main_0ee654d8.js";
        case 'vendor_js':
            return "{$site_config['paths']['baseurl']}/js/1/vendor_dcc85e11.js";
        case 'jquery_js':
            return "{$site_config['paths']['baseurl']}/js/1/jquery_acaf7162.js";
        case 'chat_main_js':
            return "{$site_config['paths']['baseurl']}/js/1/chat_main_0d6a067f.js";
        case 'chat_js':
            return "{$site_config['paths']['baseurl']}/js/1/chat_8497c973.js";
        case 'chat_log_js':
            return "{$site_config['paths']['baseurl']}/js/1/chat_log_e081be8f.js";
        case 'categories_js':
            return "{$site_config['paths']['baseurl']}/js/1/categories_5ad7e17e.js";
        case 'browse_js':
            return "{$site_config['paths']['baseurl']}/js/1/browse_de3939b1.js";
        case 'scroller_js':
            return "{$site_config['paths']['baseurl']}/js/1/scroller_c8d9f628.js";
        case 'slider_js':
            return "{$site_config['paths']['baseurl']}/js/1/slider_b7916982.js";
        case 'userdetails_js':
            return "{$site_config['paths']['baseurl']}/js/1/userdetails_88ffe01b.js";
        case 'recaptcha_js':
            return "{$site_config['paths']['baseurl']}/js/1/recaptcha_8313f33d.js";
        case 'bookmarks_js':
            return "{$site_config['paths']['baseurl']}/js/1/bookmarks_0673fe80.js";
        case 'iframe_js':
            return "{$site_config['paths']['baseurl']}/js/1/iframe_f74a311b.js";
        case 'navbar_show_js':
            return "{$site_config['paths']['baseurl']}/js/1/navbar_show_6a493036.js";
        case 'theme_js':
            return "{$site_config['paths']['baseurl']}/js/1/theme_ff3ca3dd.js";
        case 'sceditor_js':
            return "{$site_config['paths']['baseurl']}/js/1/sceditor_a570a04b.js";
        case 'cheaters_js':
            return "{$site_config['paths']['baseurl']}/js/1/cheaters_88e84984.js";
        case 'user_search_js':
            return "{$site_config['paths']['baseurl']}/js/1/user_search_79ba3068.js";
        case 'lightbox_js':
            return "{$site_config['paths']['baseurl']}/js/1/lightbox_b0c4a917.js";
        case 'tooltipster_js':
            return "{$site_config['paths']['baseurl']}/js/1/tooltipster_7883a611.js";
        case 'site_config_js':
            return "{$site_config['paths']['baseurl']}/js/1/site_config_07db2f4b.js";
        case 'checkport_js':
            return "{$site_config['paths']['baseurl']}/js/1/checkport_a540ce2b.js";
        case 'check_username_js':
            return "{$site_config['paths']['baseurl']}/js/1/check_username_ce6ba54b.js";
        case 'pStrength_js':
            return "{$site_config['paths']['baseurl']}/js/1/pStrength_1fcd76b2.js";
        case 'upload_js':
            return "{$site_config['paths']['baseurl']}/js/1/upload_229081f4.js";
        case 'request_js':
            return "{$site_config['paths']['baseurl']}/js/1/request_d5161ee2.js";
        case 'parallax_js':
            return "{$site_config['paths']['baseurl']}/js/1/parallax_eca2b578.js";
        case 'acp_js':
            return "{$site_config['paths']['baseurl']}/js/1/acp_22d19c79.js";
        case 'dragndrop_js':
            return "{$site_config['paths']['baseurl']}/js/1/dragndrop_5647940a.js";
        case 'details_js':
            return "{$site_config['paths']['baseurl']}/js/1/details_f136860e.js";
        case 'forums_js':
            return "{$site_config['paths']['baseurl']}/js/1/forums_b87eec63.js";
        case 'pollsmanager_js':
            return "{$site_config['paths']['baseurl']}/js/1/pollsmanager_801ab346.js";
        case 'trivia_js':
            return "{$site_config['paths']['baseurl']}/js/1/trivia_28839400.js";
        default:
            return null;
    }
}
